"""GET /forecast/{item_id} -- serves the pre-computed forecast plus the honest model-quality numbers.

Forecasts are generated by a batch job (`python -m app.forecasting.train`) and stored in PostgreSQL, so
this endpoint is a cheap indexed read: no model is loaded or run per request.
"""
from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Path
from psycopg import Connection

from app.db import get_conn
from app.models import ForecastPoint, ForecastResponse, ModelInfo

router = APIRouter(tags=["forecast"])
Conn = Annotated[Connection, Depends(get_conn)]

CAVEAT = ("Statistical estimate from a per-item Linear Regression (weekly lags, weekday, trend, annual "
          "seasonality). It cannot anticipate promotions, stock-outs, price changes or one-off events. "
          "Accuracy generally falls the further ahead you look; compare holdout_mae_units_per_day "
          "with the item's typical daily volume before relying on it.")


@router.get("/forecast/{item_id}", response_model=ForecastResponse, summary="Forecasted daily demand for one item")
def get_forecast(conn: Conn, item_id: Annotated[int, Path(ge=1, description="items.id")]):
    item = conn.execute("SELECT id, name, category FROM items WHERE id = %s", (item_id,)).fetchone()
    if item is None:
        raise HTTPException(404, f"item {item_id} does not exist")

    points = conn.execute(
        "SELECT forecast_date AS date, predicted_units, generated_at FROM forecasts "
        "WHERE item_id = %s ORDER BY forecast_date", (item_id,)).fetchall()
    if not points:
        raise HTTPException(404, f"no forecast for '{item['name']}': the item may be discontinued, have too little "
                                 "history, or the forecast job has not been run")

    m = conn.execute("SELECT * FROM forecast_models WHERE item_id = %s", (item_id,)).fetchone()
    model = None
    if m:
        model = ModelInfo(
            model_type=m["model_type"], trained_at=m["trained_at"],
            train_period=f"{m['train_start']} to {m['train_end']}",
            holdout_period=f"{m['test_start']} to {m['test_end']}",
            holdout_mae_units_per_day=m["test_mae"],
            holdout_wape_pct=None if m["test_wape"] is None else round(100 * m["test_wape"], 2),
            baseline_seasonal_naive_mae=m["baseline_seasonal_naive_mae"],
            baseline_mean_mae=m["baseline_mean_mae"],
            beats_seasonal_naive=None if m["baseline_seasonal_naive_mae"] is None
            else m["test_mae"] < m["baseline_seasonal_naive_mae"])

    return ForecastResponse(
        item_id=item["id"], item_name=item["name"], category=item["category"], horizon_days=len(points),
        generated_at=max(p["generated_at"] for p in points), model=model,
        forecast=[ForecastPoint(date=p["date"], predicted_units=round(p["predicted_units"], 2)) for p in points],
        caveat=CAVEAT)
